name: HelloWorld CI

on:
  push:
    branches: [master]

permissions:
  checks: write

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}

jobs:
  run-hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: R2026a

      - name: Run HelloWord script
        uses: matlab-actions/run-command@v3
        with:
          command: 
            openProject("HelloWorld.prj"); 
            HelloWord;

